"""initial schema

Creates the full schema from the SQLAlchemy metadata. Subsequent changes should use
autogenerated revisions (`make revision m="..."`).

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-03
"""
from alembic import op

from app.database import Base

# Import models so every table registers on Base.metadata.
import app.models  # noqa: F401

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    bind = op.get_bind()
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
